version: '3'

services:
  polipo:
    image: lesca/polipo:arm32v7
    restart: always
    hostname: polipo
    container_name: polipo
    ports:
      - "8123:8123/tcp"
    volumes:
      - ./polipo/config:/etc/polipo/config
